//! Compile-error tests for `#[api_endpoint]`, verified with `trybuild`.
//!
//! Each `.rs` file in `tests/fixtures/fail/` is expected to produce a compile
//! error. The corresponding `.stderr` file (auto-generated by running
//! `TRYBUILD=overwrite cargo test compile_errors`) captures the exact error
//! message so future runs can detect regressions.

/// Verify that each fixture in `tests/fixtures/fail/` produces the expected compile error.
///
/// To regenerate `.stderr` snapshots after changing error messages, run:
/// ```text
/// TRYBUILD=overwrite cargo test -p api-macros --test compile_errors
/// ```
#[test]
fn compile_errors() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/fixtures/fail/*.rs");
}
