//! Convert extracted Rust types to TypeScript type strings and generate `.ts` file content.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use syn::{GenericArgument, PathArguments, Type, TypePath, TypeTuple};

use crate::type_extract::ExtractedRole;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Generate the full TypeScript file content for one endpoint.
///
/// Returns the file content as a `String`, or a [`syn::Error`] if the function signature
/// contains a type that cannot be converted to TypeScript.
pub(crate) fn generate_ts_file(
    ts_name: &str,
    method: &str,
    path: &str,
    query: Option<&Type>,
    body: Option<&Type>,
    path_params: Option<&Type>,
    response: &ExtractedRole,
) -> syn::Result<String> {
    let mut imports: BTreeSet<String> = BTreeSet::new();

    let query_ts = query.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let body_ts = body.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let path_params_ts = path_params.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let response_ts = match response {
        ExtractedRole::Single(t) => rust_type_to_ts(t, &mut imports)?,
        ExtractedRole::Union(a, b) => {
            let a_ts = rust_type_to_ts(a, &mut imports)?;
            let b_ts = rust_type_to_ts(b, &mut imports)?;
            format!("{a_ts} | {b_ts}")
        }
    };

    // TypeScript doesn't allow `import type { X }` and `export type X = X` to share the same
    // local name. Detect the conflict: when a role alias would equal the imported type name
    // (e.g. `export type FooBody = FooBody`), we use a re-export form instead:
    //   `export type { FooBody } from '../FooBody';`
    // That form creates no local binding and therefore never conflicts.
    let roles = [
        (format!("{ts_name}Query"), &query_ts),
        (format!("{ts_name}Body"), &body_ts),
        (format!("{ts_name}PathParams"), &path_params_ts),
        (format!("{ts_name}Response"), &response_ts),
    ];
    let mut re_exports: BTreeSet<String> = BTreeSet::new();
    for (alias, ts_type) in &roles {
        if alias == ts_type.as_str() && imports.contains(ts_type.as_str()) {
            imports.remove(ts_type.as_str());
            re_exports.insert((*ts_type).clone());
        }
    }

    let mut out = String::new();
    out.push_str(
        "// This file was generated by the api_endpoint macro. Do not edit this file manually.\n",
    );

    if !imports.is_empty() {
        out.push('\n');
        for import in &imports {
            let _ = writeln!(out, "import type {{ {import} }} from \"../{import}\";");
        }
    }
    // EndpointSpec is a phantom-typed descriptor consumed by callEndpoint in http.ts.
    let _ = writeln!(
        out,
        "import type {{ EndpointSpec }} from \"client/services/http\";"
    );

    let _ = write!(
        out,
        "\nexport const {ts_name}Method = \"{method}\" as const;"
    );
    let _ = writeln!(out, "\nexport const {ts_name}Path   = \"{path}\" as const;");

    for (alias, ts_type) in &roles {
        if re_exports.contains(ts_type.as_str()) {
            // No local binding — use re-export to avoid TS2440.
            let _ = writeln!(out, "export type {{ {ts_type} }} from \"../{ts_type}\";");
        } else {
            let _ = writeln!(out, "export type  {alias} = {ts_type};");
        }
    }

    // Typed spec object — `satisfies` validates at compile time without unsafe casting.
    // Role aliases ({ts_name}Query, {ts_name}Body, etc.) are used as the phantom type
    // params so this always compiles even when they resolve to `never`.
    let _ = writeln!(
        out,
        "\nexport default {{\n    \
             method: {ts_name}Method,\n    \
             path: {ts_name}Path,\n\
         }} satisfies EndpointSpec<\n    \
             {ts_name}Query,\n    \
             {ts_name}Body,\n    \
             {ts_name}PathParams,\n    \
             {ts_name}Response\n\
         >;",
    );

    Ok(out)
}

/// Generate the content of `generated/api/<TsName>.ts` — a thin typed wrapper
/// that calls `callEndpoint` with the endpoint's spec and the appropriate arguments.
///
/// Parameters:
/// - `ts_name`         — PascalCase endpoint name (e.g. `"GetUserInfo"`).
/// - `fn_name`         — camelCase TypeScript function name (e.g. `"getUserInfo"`).
/// - `has_query`       — whether the endpoint has a query-string type (not `never`).
/// - `has_body`        — whether the endpoint has a request-body type (not `never`).
/// - `has_path_params` — whether the endpoint has path-parameter types (not `never`).
pub(crate) fn generate_api_file(
    ts_name: &str,
    fn_name: &str,
    has_query: bool,
    has_body: bool,
    has_path_params: bool,
) -> String {
    let mut out = String::new();
    out.push_str(
        "// This file was generated by the api_endpoint macro. Do not edit this file manually.\n",
    );

    // Default import for the spec; local alias `spec` is used in the callEndpoint call.
    let _ = writeln!(out, "\nimport spec from \"bindings/endpoints/{ts_name}\";");

    // Type-only imports for parameter and return-type annotations.
    let mut type_imports: Vec<String> = Vec::new();
    if has_query {
        type_imports.push(format!("{ts_name}Query"));
    }
    if has_body {
        type_imports.push(format!("{ts_name}Body"));
    }
    if has_path_params {
        type_imports.push(format!("{ts_name}PathParams"));
    }
    type_imports.push(format!("{ts_name}Response")); // always needed for the return type
    let _ = writeln!(
        out,
        "import type {{ {} }} from \"bindings/endpoints/{ts_name}\";",
        type_imports.join(", ")
    );
    // ApiResult wraps every response; callEndpoint now returns Promise<ApiResult<R>>.
    let _ = writeln!(
        out,
        "import type {{ ApiResult }} from \"bindings/ApiResult\";"
    );

    // callEndpoint only throws on network/parse failures; HTTP errors are in ApiResult.success.
    let _ = writeln!(
        out,
        "import {{ callEndpoint }} from \"client/services/http\";"
    );

    // Function signature — required params first (pathParams, body), optional last (query).
    let _ = writeln!(out, "\nexport async function {fn_name}(");
    if has_path_params {
        let _ = writeln!(out, "    pathParams: {ts_name}PathParams,");
    }
    if has_body {
        let _ = writeln!(out, "    body: {ts_name}Body,");
    }
    if has_query {
        let _ = writeln!(out, "    query?: {ts_name}Query,");
    }
    let _ = writeln!(out, "): Promise<ApiResult<{ts_name}Response>> {{");

    // Explicit type parameters avoid phantom-type inference ambiguity: TypeScript cannot
    // infer Q/B/P/R from the spec value alone because EndpointSpec's type params are phantom.
    // Use `never` directly for absent roles so we avoid importing names just for type params.
    let query_tp = if has_query {
        format!("{ts_name}Query")
    } else {
        "never".to_owned()
    };
    let body_tp = if has_body {
        format!("{ts_name}Body")
    } else {
        "never".to_owned()
    };
    let path_params_tp = if has_path_params {
        format!("{ts_name}PathParams")
    } else {
        "never".to_owned()
    };
    let explicit_type_params =
        format!("{query_tp}, {body_tp}, {path_params_tp}, {ts_name}Response");

    let mut call_args: Vec<&str> = Vec::new();
    if has_query {
        call_args.push("query");
    }
    if has_body {
        call_args.push("body");
    }
    if has_path_params {
        call_args.push("pathParams");
    }

    if call_args.is_empty() {
        let _ = writeln!(
            out,
            "    return callEndpoint<{explicit_type_params}>(spec);"
        );
    } else {
        let _ = writeln!(
            out,
            "    return callEndpoint<{explicit_type_params}>(spec, {{ {} }});",
            call_args.join(", ")
        );
    }
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Rust type → TypeScript string conversion
// ---------------------------------------------------------------------------

/// Recursively convert a Rust `syn::Type` to a TypeScript type string.
/// Named types that are not primitives are added to `imports`.
///
/// Returns a [`syn::Error`] for any type that has no TypeScript equivalent
/// (e.g. slices, raw pointers, non-unit tuples, bare `Vec`/`Option` without
/// generic arguments).
pub(crate) fn rust_type_to_ts(ty: &Type, imports: &mut BTreeSet<String>) -> syn::Result<String> {
    match ty {
        // Unit tuple `()` → `null`
        Type::Tuple(TypeTuple { elems, .. }) if elems.is_empty() => Ok("null".to_owned()),

        // Path types: primitives, Vec<T>, Option<T>, named types
        Type::Path(TypePath { path, .. }) => {
            let last = path
                .segments
                .last()
                .expect("type path has at least one segment");
            let name = last.ident.to_string();

            match name.as_str() {
                // Boolean
                "bool" => Ok("boolean".to_owned()),

                // Numeric primitives
                "f32" | "f64" | "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16"
                | "i32" | "i64" | "i128" | "isize" => Ok("number".to_owned()),

                // String types
                "String" | "str" => Ok("string".to_owned()),

                // Vec<T> → Array<T>
                "Vec" => {
                    if let PathArguments::AngleBracketed(ab) = &last.arguments
                        && let Some(GenericArgument::Type(inner)) = ab.args.first()
                    {
                        let inner_ts = rust_type_to_ts(inner, imports)?;
                        return Ok(format!("Array<{inner_ts}>"));
                    }
                    Err(syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: `Vec` without a type argument is not supported \
                         in endpoint signatures",
                    ))
                }

                // Option<T> → T | null
                "Option" => {
                    if let PathArguments::AngleBracketed(ab) = &last.arguments
                        && let Some(GenericArgument::Type(inner)) = ab.args.first()
                    {
                        let inner_ts = rust_type_to_ts(inner, imports)?;
                        return Ok(format!("{inner_ts} | null"));
                    }
                    Err(syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: `Option` without a type argument is not supported \
                         in endpoint signatures",
                    ))
                }

                // Everything else is treated as a named type from bindings/
                other => {
                    imports.insert(other.to_owned());
                    Ok(other.to_owned())
                }
            }
        }

        // Fixed-size array `[T; N]` → TypeScript tuple `[T, T, ..., T]` (N elements)
        Type::Array(arr) => {
            let elem_ts = rust_type_to_ts(&arr.elem, imports)?;
            let len = match &arr.len {
                syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Int(n),
                    ..
                }) => n.base10_parse::<usize>().map_err(|_| {
                    syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: array length is not a valid usize",
                    )
                })?,
                _ => {
                    return Err(syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: only literal array lengths are supported \
                         in endpoint signatures",
                    ));
                }
            };
            let elems = std::iter::repeat_n(elem_ts.as_str(), len)
                .collect::<Vec<_>>()
                .join(", ");
            Ok(format!("[{elems}]"))
        }

        // Reference `&T` → treat as `T`
        Type::Reference(r) => rust_type_to_ts(&r.elem, imports),

        // Anything else (slices, raw pointers, non-unit tuples, impl Trait, etc.) → error
        _ => Err(syn::Error::new_spanned(
            ty,
            "#[api_endpoint]: unsupported type in endpoint signature; only named types, \
             bool, numeric primitives, String, Vec<T>, Option<T>, [T; N], () and &T are supported",
        )),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use syn::Type;

    fn parse_type(s: &str) -> Type {
        syn::parse_str(s).expect("valid Rust type expression")
    }

    // ------------------------------------------------------------------
    // rust_type_to_ts: primitive conversions
    // ------------------------------------------------------------------

    #[test]
    fn ts_bool() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("bool"), &mut imp).unwrap(),
            "boolean"
        );
        assert!(imp.is_empty(), "no imports for primitives");
    }

    #[test]
    fn ts_numerics() {
        for ty in &[
            "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize",
            "f32", "f64",
        ] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "number",
                "numeric type {ty} should map to number"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_strings() {
        for ty in &["String", "str"] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "string",
                "string type {ty} should map to string"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_unit() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("()"), &mut imp).unwrap(),
            "null"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_vec() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Vec<u32>"), &mut imp).unwrap(),
            "Array<number>"
        );
        assert!(imp.is_empty(), "Vec<primitive> needs no imports");
    }

    #[test]
    fn ts_vec_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("Vec<CredentialInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "Array<CredentialInfo>");
        assert!(
            imp.contains("CredentialInfo"),
            "inner named type added to imports"
        );
    }

    #[test]
    fn ts_option() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Option<String>"), &mut imp).unwrap(),
            "string | null"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_option_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("Option<UserInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "UserInfo | null");
        assert!(imp.contains("UserInfo"));
    }

    #[test]
    fn ts_named_type_adds_import() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("TrendsResponse"), &mut imp).unwrap();
        assert_eq!(ts, "TrendsResponse");
        assert!(imp.contains("TrendsResponse"));
    }

    // ------------------------------------------------------------------
    // rust_type_to_ts: unsupported types produce errors
    // ------------------------------------------------------------------

    #[test]
    fn ts_slice_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("[u8]"), &mut imp).is_err(),
            "slice type should not be silently accepted"
        );
    }

    #[test]
    fn ts_non_unit_tuple_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("(A, B)"), &mut imp).is_err(),
            "non-unit tuple should not be silently accepted"
        );
    }

    #[test]
    fn ts_vec_without_args_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("Vec"), &mut imp).is_err(),
            "bare Vec without type argument should not be silently accepted"
        );
    }

    #[test]
    fn ts_option_without_args_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("Option"), &mut imp).is_err(),
            "bare Option without type argument should not be silently accepted"
        );
    }

    #[test]
    fn ts_fixed_array_primitives() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[String; 10]"), &mut imp).unwrap();
        assert_eq!(
            ts,
            "[string, string, string, string, string, string, string, string, string, string]"
        );
        assert!(imp.is_empty(), "no imports for primitive element type");
    }

    #[test]
    fn ts_fixed_array_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[BackupCode; 3]"), &mut imp).unwrap();
        assert_eq!(ts, "[BackupCode, BackupCode, BackupCode]");
        assert!(
            imp.contains("BackupCode"),
            "inner named type added to imports"
        );
    }

    #[test]
    fn ts_fixed_array_size_zero() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[u32; 0]"), &mut imp).unwrap();
        assert_eq!(ts, "[]");
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 1 — GET with query type
    // ------------------------------------------------------------------

    #[test]
    fn generate_get_with_query() {
        // FromToQuery and TrendsResponse have different names than the role aliases
        // (GetTrendsQuery, GetTrendsResponse), so they use the import + type alias path.
        let query = parse_type("FromToQuery");
        let response = ExtractedRole::Single(Box::new(parse_type("TrendsResponse")));
        let content = generate_ts_file(
            "GetTrends",
            "GET",
            "measurement/trends",
            Some(&query),
            None,
            None,
            &response,
        )
        .unwrap();
        assert!(
            content.contains("export const GetTrendsMethod = \"GET\" as const;"),
            "method const"
        );
        assert!(
            content.contains("export const GetTrendsPath   = \"measurement/trends\" as const;"),
            "path const"
        );
        assert!(
            content.contains("export type  GetTrendsQuery = FromToQuery;"),
            "query type alias"
        );
        assert!(
            content.contains("export type  GetTrendsBody = never;"),
            "body never alias"
        );
        assert!(
            content.contains("export type  GetTrendsPathParams = never;"),
            "path params never alias"
        );
        assert!(
            content.contains("export type  GetTrendsResponse = TrendsResponse;"),
            "response type alias"
        );
        assert!(
            content.contains("import type { FromToQuery } from \"../FromToQuery\";"),
            "query import"
        );
        assert!(
            content.contains("import type { TrendsResponse } from \"../TrendsResponse\";"),
            "response import"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 2 — POST with body type (non-conflicting names)
    // ------------------------------------------------------------------

    #[test]
    fn generate_post_with_body() {
        // Use CredentialsBody as the body type: the role alias is LoginBody ≠ CredentialsBody,
        // so this exercises the import + type alias path (not the re-export path).
        let body = parse_type("CredentialsBody");
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let content = generate_ts_file(
            "Login",
            "POST",
            "auth/login",
            None,
            Some(&body),
            None,
            &response,
        )
        .unwrap();
        assert!(content.contains("export const LoginMethod = \"POST\" as const;"));
        assert!(content.contains("export const LoginPath   = \"auth/login\" as const;"));
        assert!(content.contains("export type  LoginQuery = never;"));
        assert!(content.contains("export type  LoginBody = CredentialsBody;"));
        assert!(content.contains("export type  LoginPathParams = never;"));
        assert!(content.contains("export type  LoginResponse = ExpiresIn;"));
        assert!(content.contains("import type { CredentialsBody } from \"../CredentialsBody\";"));
        assert!(content.contains("import type { ExpiresIn } from \"../ExpiresIn\";"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: conflicting alias — uses re-export form
    // ------------------------------------------------------------------

    #[test]
    fn generate_conflicting_alias_uses_re_export() {
        // When the body type name equals the role alias name (e.g. endpoint "PatchInfo"
        // has body type PatchInfoBody → alias PatchInfoBody), TypeScript would error with
        // TS2440. We must emit `export type { PatchInfoBody } from '../PatchInfoBody'`
        // instead.
        let body = parse_type("PatchInfoBody");
        let response = ExtractedRole::Single(Box::new(parse_type("()")));
        let content = generate_ts_file(
            "PatchInfo",
            "PATCH",
            "user/info",
            None,
            Some(&body),
            None,
            &response,
        )
        .unwrap();
        // Re-export form: no local binding conflict
        assert!(
            content.contains("export type { PatchInfoBody } from \"../PatchInfoBody\";"),
            "conflicting body alias uses re-export form"
        );
        // No import line for the conflicting type
        assert!(
            !content.contains("import type { PatchInfoBody }"),
            "conflicting type must not appear as a regular import"
        );
        // The standard type alias line must NOT be present
        assert!(
            !content.contains("export type  PatchInfoBody = PatchInfoBody;"),
            "conflicting alias form must not be emitted"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 3 — web::Path<String> → string (no import)
    // ------------------------------------------------------------------

    #[test]
    fn generate_with_string_path_params() {
        let path_params = parse_type("String");
        let response = ExtractedRole::Single(Box::new(parse_type("()")));
        let content = generate_ts_file(
            "DeleteCredential",
            "DELETE",
            "user/webauthn/credentials/{id}",
            None,
            None,
            Some(&path_params),
            &response,
        )
        .unwrap();
        assert!(
            content.contains("export type  DeleteCredentialPathParams = string;"),
            "String path param → 'string' in TypeScript"
        );
        // `string` is a primitive — no import for it
        assert!(
            !content.contains("import type { string }"),
            "no spurious import for string primitive"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 4 — CustomizedJsonApiResult response
    // (at the ts_gen level this is just a named type in ExtractedRole::Single)
    // ------------------------------------------------------------------

    #[test]
    fn generate_customized_response() {
        // After the macro peels CustomizedJsonApiResult<T>, ts_gen only sees T.
        // So this verifies the Single(T) path with a non-conflicting name.
        let response = ExtractedRole::Single(Box::new(parse_type("MeasurementEntry")));
        let content = generate_ts_file(
            "PatchMeasurement",
            "PATCH",
            "measurement",
            None,
            None,
            None,
            &response,
        )
        .unwrap();
        assert!(content.contains("export type  PatchMeasurementResponse = MeasurementEntry;"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: union response (Either<A, B>)
    // ------------------------------------------------------------------

    #[test]
    fn generate_union_response() {
        let response =
            ExtractedRole::Union(Box::new(parse_type("TypeA")), Box::new(parse_type("TypeB")));
        let content = generate_ts_file(
            "TestUnion",
            "GET",
            "test/union",
            None,
            None,
            None,
            &response,
        )
        .unwrap();
        assert!(content.contains("export type  TestUnionResponse = TypeA | TypeB;"));
        assert!(content.contains("import type { TypeA } from \"../TypeA\";"));
        assert!(content.contains("import type { TypeB } from \"../TypeB\";"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: spec constant and EndpointSpec import
    // ------------------------------------------------------------------

    #[test]
    fn generate_ts_file_includes_endpoint_spec_import() {
        let response = ExtractedRole::Single(Box::new(parse_type("User")));
        let content = generate_ts_file(
            "GetUserInfo",
            "GET",
            "user/info",
            None,
            None,
            None,
            &response,
        )
        .unwrap();
        assert!(
            content.contains("import type { EndpointSpec } from \"client/services/http\";"),
            "EndpointSpec import should be present"
        );
        assert!(
            content.contains("satisfies EndpointSpec<"),
            "default export with satisfies clause should be present"
        );
        assert!(
            content.contains("GetUserInfoQuery,"),
            "spec type params should use role alias names"
        );
        assert!(
            content.contains("GetUserInfoResponse"),
            "spec type params should use role alias names"
        );
    }

    #[test]
    fn generate_ts_file_spec_default_export() {
        let body = parse_type("LoginBody");
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let content = generate_ts_file(
            "PostAuthLogin",
            "POST",
            "auth/login",
            None,
            Some(&body),
            None,
            &response,
        )
        .unwrap();
        assert!(
            content.contains("export default {"),
            "spec should be a default export"
        );
        assert!(
            content.contains("method: PostAuthLoginMethod,"),
            "spec should reference method const"
        );
        assert!(
            content.contains("path: PostAuthLoginPath,"),
            "spec should reference path const"
        );
    }

    // ------------------------------------------------------------------
    // generate_api_file
    // ------------------------------------------------------------------

    #[test]
    fn generate_api_get_with_query() {
        let content = generate_api_file("GetUserInfo", "getUserInfo", true, false, false);
        assert!(
            content.contains("import spec from \"bindings/endpoints/GetUserInfo\";"),
            "default spec import"
        );
        assert!(
            content.contains("import type { GetUserInfoQuery, GetUserInfoResponse }"),
            "type imports include only non-never role types"
        );
        // GetUserInfoBody and GetUserInfoPathParams are absent roles; `never` is emitted
        // directly in the callEndpoint<> type params so no import is needed.
        assert!(
            !content.contains("import type { GetUserInfoBody"),
            "body alias must not appear in the import type statement"
        );
        assert!(
            !content.contains("import type { GetUserInfoPathParams"),
            "pathParams alias must not appear in the import type statement"
        );
        assert!(
            content.contains("export async function getUserInfo("),
            "function exported with camelCase name"
        );
        assert!(
            content.contains("query?: GetUserInfoQuery,"),
            "optional query parameter"
        );
        assert!(
            content.contains("): Promise<ApiResult<GetUserInfoResponse>> {"),
            "return type wraps Response in ApiResult"
        );
        assert!(
            content.contains("import type { ApiResult } from \"bindings/ApiResult\";"),
            "ApiResult imported from bindings"
        );
        // Absent roles use `never` directly in type params (not the alias name) so no extra import needed.
        assert!(
            content.contains("callEndpoint<GetUserInfoQuery, never, never, GetUserInfoResponse>"),
            "explicit type params: absent roles use never, not alias names"
        );
        assert!(
            content.contains("spec, { query }"),
            "query arg passed to callEndpoint"
        );
    }

    #[test]
    fn generate_api_post_with_body() {
        let content = generate_api_file("PostAuthLogin", "postAuthLogin", false, true, false);
        assert!(
            content.contains("body: PostAuthLoginBody,"),
            "required body parameter"
        );
        assert!(
            !content.contains("query?:"),
            "no query parameter when has_query=false"
        );
        assert!(
            content.contains("spec, { body }"),
            "body arg passed to callEndpoint"
        );
    }

    #[test]
    fn generate_api_delete_with_path_params() {
        let content = generate_api_file(
            "DeleteUserWebauthnCredentialsId",
            "deleteUserWebauthnCredentialsId",
            false,
            false,
            true,
        );
        assert!(
            content.contains("pathParams: DeleteUserWebauthnCredentialsIdPathParams,"),
            "required pathParams parameter"
        );
        assert!(
            content.contains("spec, { pathParams }"),
            "pathParams arg passed to callEndpoint"
        );
    }

    #[test]
    fn generate_api_no_params() {
        let content = generate_api_file("PostAuthLogout", "postAuthLogout", false, false, false);
        assert!(!content.contains("query?:"), "no query parameter");
        assert!(!content.contains("body:"), "no body parameter");
        assert!(!content.contains("pathParams:"), "no pathParams parameter");
        // No args object — callEndpoint called with spec only; all absent roles → never
        assert!(
            content.contains("callEndpoint<never, never, never, PostAuthLogoutResponse>(spec);"),
            "no args object when no params; all roles are never"
        );
    }

    #[test]
    fn generate_api_camel_case_name() {
        use heck::ToLowerCamelCase as _;
        assert_eq!("GetUserInfo".to_lower_camel_case(), "getUserInfo");
        assert_eq!(
            "PostAuthWebauthn2faComplete".to_lower_camel_case(),
            "postAuthWebauthn2faComplete"
        );
        assert_eq!(
            "DeleteUserWebauthnCredentialsId".to_lower_camel_case(),
            "deleteUserWebauthnCredentialsId"
        );
    }

    // ------------------------------------------------------------------
    // Imports are deduplicated and sorted alphabetically
    // ------------------------------------------------------------------

    #[test]
    fn imports_are_sorted_and_deduped() {
        // Use the same named type twice (in body and response) → one import
        let body = parse_type("SharedType");
        let response = ExtractedRole::Single(Box::new(parse_type("AnotherType")));
        let content = generate_ts_file(
            "TestDedup",
            "POST",
            "test/dedup",
            None,
            Some(&body),
            None,
            &response,
        )
        .unwrap();
        let import_lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("import type"))
            .collect();
        // AnotherType and SharedType come from the BTreeSet (sorted); EndpointSpec is always last
        assert_eq!(import_lines.len(), 3);
        assert!(import_lines[0].contains("AnotherType"));
        assert!(import_lines[1].contains("SharedType"));
        assert!(import_lines[2].contains("EndpointSpec"));
    }
}
