//! Convert extracted Rust types to TypeScript type strings and generate `.ts` file content.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use syn::{GenericArgument, PathArguments, Type, TypePath, TypeSlice, TypeTuple};

use crate::type_extract::ExtractedRole;

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Generate the full TypeScript file content for one endpoint.
///
/// Returns the file content as a `String`, or a [`syn::Error`] if the function signature
/// contains a type that cannot be converted to TypeScript.
#[expect(clippy::too_many_arguments)]
pub(crate) fn generate_ts_file(
    ts_name: &str,
    method: &str,
    path: &str,
    query: Option<&Type>,
    body: Option<&Type>,
    path_params: Option<&Type>,
    response: &ExtractedRole,
    field_errors: Option<&Type>,
    models_path: &str,
) -> syn::Result<String> {
    let mut imports: BTreeSet<String> = BTreeSet::new();

    let query_ts = query.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let body_ts = body.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let path_params_ts = path_params.map_or_else(
        || Ok("never".to_owned()),
        |t| rust_type_to_ts(t, &mut imports),
    )?;
    let response_ts = match response {
        ExtractedRole::Single(t) => rust_type_to_ts(t, &mut imports)?,
        ExtractedRole::Union(a, b) => {
            let a_ts = rust_type_to_ts(a, &mut imports)?;
            let b_ts = rust_type_to_ts(b, &mut imports)?;
            format!("{a_ts} | {b_ts}")
        }
    };
    let field_errors_ts = field_errors
        .map(|t| rust_type_to_ts(t, &mut imports))
        .transpose()?;

    // TypeScript doesn't allow `import type { X }` and `export type X = X` to share the same
    // local name (TS2440). Detect the conflict: when a role alias would equal the imported type
    // name (e.g. `export type FooBody = FooBody`), keep the normal `import type { X }` (so the
    // local binding is available to the `satisfies` block) and emit `export type { X }` (bare
    // re-export, no `from`) instead of the alias form.
    let mut roles = vec![
        (format!("{ts_name}Query"), query_ts),
        (format!("{ts_name}Body"), body_ts),
        (format!("{ts_name}PathParams"), path_params_ts),
        (format!("{ts_name}Response"), response_ts),
    ];
    // Only present when `field_errors` was given; `EndpointSpec`'s 5th type param defaults to
    // `never`, so omitting this role entirely (rather than emitting `= never`) keeps endpoints
    // without field errors generating byte-identical output to before this feature existed.
    if let Some(field_errors_ts) = field_errors_ts {
        roles.push((format!("{ts_name}FieldErrors"), field_errors_ts));
    }
    let mut re_exports: BTreeSet<String> = BTreeSet::new();
    for (alias, ts_type) in &roles {
        if alias == ts_type && imports.contains(ts_type.as_str()) {
            // Keep the type in `imports` so `import type { X }` creates a local binding
            // (required for the `satisfies` block). We'll emit `export type { X }` (no `from`)
            // to re-export that binding without triggering TS2440.
            re_exports.insert(ts_type.clone());
        }
    }

    let mut out = String::new();
    out.push_str(
        "// This file was generated by the api_endpoint macro. Do not edit this file manually.\n",
    );

    if !imports.is_empty() {
        out.push('\n');
        for import in &imports {
            let _ = writeln!(
                out,
                "import type {{ {import} }} from \"{models_path}/{import}\";"
            );
        }
    }
    // EndpointSpec is a phantom-typed descriptor; the type definition lives in EndpointSpec.ts,
    // which is copied into the same directory as the generated endpoint binding files.
    let _ = writeln!(
        out,
        "import type {{ EndpointSpec }} from \"./EndpointSpec\";"
    );

    let _ = write!(
        out,
        "\nexport const {ts_name}Method = \"{method}\" as const;"
    );
    let _ = writeln!(out, "\nexport const {ts_name}Path   = \"{path}\" as const;");

    for (alias, ts_type) in &roles {
        if re_exports.contains(ts_type.as_str()) {
            // Re-export the locally-imported binding to avoid TS2440 (`export type X = X` is
            // illegal when X is also an import). `export type { X }` is valid and keeps the
            // local binding visible to the `satisfies` block below.
            let _ = writeln!(out, "export type {{ {ts_type} }};");
        } else {
            let _ = writeln!(out, "export type  {alias} = {ts_type};");
        }
    }

    // Typed spec object — `satisfies` validates at compile time without unsafe casting.
    // Role aliases ({ts_name}Query, {ts_name}Body, etc.) are used as the phantom type
    // params so this always compiles even when they resolve to `never`.
    let field_errors_arg = if field_errors.is_some() {
        format!(",\n    {ts_name}FieldErrors")
    } else {
        String::new()
    };
    let _ = writeln!(
        out,
        "\nexport default {{\n    \
             method: {ts_name}Method,\n    \
             path: {ts_name}Path,\n\
         }} satisfies EndpointSpec<\n    \
             {ts_name}Query,\n    \
             {ts_name}Body,\n    \
             {ts_name}PathParams,\n    \
             {ts_name}Response{field_errors_arg}\n\
         >;",
    );

    Ok(out)
}

/// Which optional roles an endpoint has, beyond the always-present response type.
#[derive(Clone, Copy, Debug)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "each field is an independent, named yes/no role flag; a bitflags enum would \
              add ceremony without adding clarity here"
)]
pub(crate) struct ApiFileRoles {
    /// Whether the endpoint has a query-string type (not `never`).
    pub(crate) has_query: bool,
    /// Whether the endpoint has a request-body type (not `never`).
    pub(crate) has_body: bool,
    /// Whether the endpoint has path-parameter types (not `never`).
    pub(crate) has_path_params: bool,
    /// Whether the endpoint declared `field_errors = "..."`.
    pub(crate) has_field_errors: bool,
}

/// Computes the relative TS module path from the directory `from` to the directory `to`,
/// where both are given relative to the same root (e.g. `APIM_EXPORT_DIR`). Used so that
/// generated files can import each other by filesystem-relative path.
///
/// Examples (from -> to => result): `"api" -> "bindings/endpoints"` => `"../bindings/endpoints"`;
/// `"api" -> "endpoints"` => `"../endpoints"`; `"api" -> "api"` => `"."`.
fn relative_module_dir(from: &str, to: &str) -> String {
    let from_segments: Vec<&str> = from.split('/').filter(|s| !s.is_empty()).collect();
    let to_segments: Vec<&str> = to.split('/').filter(|s| !s.is_empty()).collect();

    let common_len = from_segments
        .iter()
        .zip(to_segments.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let ups = from_segments.len() - common_len;
    let mut parts: Vec<&str> = Vec::new();
    parts.extend(std::iter::repeat_n("..", ups));
    parts.extend(&to_segments[common_len..]);

    if parts.is_empty() {
        ".".to_owned()
    } else if parts[0] == ".." {
        parts.join("/")
    } else {
        format!("./{}", parts.join("/"))
    }
}

/// Writes the `import`/`import type` lines for `<api_path>/<TsName>.ts` into `out`, returning
/// the response-wrapper type name to use in the function's return-type annotation (`None` in
/// unwrapped mode, where there is no wrapper).
fn write_api_imports(
    out: &mut String,
    ts_name: &str,
    roles: ApiFileRoles,
    config: &crate::config::MacroConfig,
) {
    let endpoints_path = relative_module_dir(&config.api_path, &config.endpoints_path);
    let call_endpoint_name = &config.call_endpoint_name;
    let call_endpoint_module = config
        .call_endpoint_module()
        .expect("call_endpoint_module is validated before generate_api_file is called");

    // Default import for the spec; local alias `spec` is used in the callEndpoint call.
    let _ = writeln!(out, "\nimport spec from \"{endpoints_path}/{ts_name}\";");

    // Type-only imports for parameter and return-type annotations.
    let mut type_imports: Vec<String> = Vec::new();
    if roles.has_query {
        type_imports.push(format!("{ts_name}Query"));
    }
    if roles.has_body {
        type_imports.push(format!("{ts_name}Body"));
    }
    if roles.has_path_params {
        type_imports.push(format!("{ts_name}PathParams"));
    }
    type_imports.push(format!("{ts_name}Response")); // always needed for the return type
    if roles.has_field_errors && !config.unwrapped_response {
        type_imports.push(format!("{ts_name}FieldErrors"));
    }
    let _ = writeln!(
        out,
        "import type {{ {} }} from \"{endpoints_path}/{ts_name}\";",
        type_imports.join(", ")
    );
    // In wrapped mode, every response is wrapped in `typed_result_type` (see the
    // `TypedApiResult` doc comment for why a plain `result_type<R>` would be dishonest about
    // what `success: false` responses actually carry, even for endpoints with no
    // `field_errors` — its `Fe` type parameter just defaults to `never` for those).
    // In unwrapped mode the wrapper is absent, so no import is needed.
    if !config.unwrapped_response {
        let typed_result_type = &config.typed_result_type;
        let typed_result_path = &config.typed_result_path;
        let _ = writeln!(
            out,
            "import type {{ {typed_result_type} }} from \"{typed_result_path}\";"
        );
    }

    // callEndpoint only throws on network/parse failures; HTTP errors are in ApiResult.success.
    let _ = writeln!(
        out,
        "import {{ {call_endpoint_name} }} from \"{call_endpoint_module}\";"
    );
}

/// Generate the content of `<api_path>/<TsName>.ts` — a thin typed wrapper
/// that calls `callEndpoint` with the endpoint's spec and the appropriate arguments.
///
/// Parameters:
/// - `ts_name`  — `PascalCase` endpoint name (e.g. `"GetUserInfo"`).
/// - `fn_name`  — camelCase TypeScript function name (e.g. `"getUserInfo"`).
/// - `roles`    — which optional roles the endpoint has (see [`ApiFileRoles`]).
/// - `config`   - the configuration values extracted from the environment:
///   - `call_endpoint_module` — TS module path for the `callEndpoint` import.
///   - `call_endpoint_name`   — exported name of the `callEndpoint` function.
///   - `endpoints_path`       — sub-path (relative to `export_dir`) where endpoint binding
///     files live; the spec import is computed relative to `api_path` from this.
///   - `result_type`          — name of the response-wrapper type (e.g. `"ApiResult"`).
///   - `result_path`          — TS module path to import `result_type` from.
///   - `typed_result_type`    — name of the discriminated wrapper type used when
///     `roles.has_field_errors` is set (e.g. `"TypedApiResult"`).
///   - `typed_result_path`    — TS module path to import `typed_result_type` from.
pub(crate) fn generate_api_file(
    ts_name: &str,
    fn_name: &str,
    roles: ApiFileRoles,
    config: &crate::config::MacroConfig,
) -> String {
    let mut out = String::new();
    out.push_str(
        "// This file was generated by the api_endpoint macro. Do not edit this file manually.\n",
    );

    write_api_imports(&mut out, ts_name, roles, config);

    let typed_result_type = &config.typed_result_type;
    // `Fe` for `TypedApiResult<R, Fe>`/`callEndpoint<Q, B, P, R, Fe>`: the endpoint's declared
    // field-errors type, or bare `never` (no import needed) when it didn't declare one.
    let field_errors_tp = if roles.has_field_errors {
        format!("{ts_name}FieldErrors")
    } else {
        "never".to_owned()
    };

    // Function signature — required params first (pathParams, body), optional last (query, options).
    let _ = writeln!(out, "\nexport async function {fn_name}(");
    if roles.has_path_params {
        let _ = writeln!(out, "    pathParams: {ts_name}PathParams,");
    }
    if roles.has_body {
        let _ = writeln!(out, "    body: {ts_name}Body,");
    }
    if roles.has_query {
        let _ = writeln!(out, "    query?: {ts_name}Query,");
    }
    let _ = writeln!(out, "    options?: Omit<RequestInit, \"method\">,");
    if config.unwrapped_response {
        let _ = writeln!(out, "): Promise<{ts_name}Response> {{");
    } else {
        let _ = writeln!(
            out,
            "): Promise<{typed_result_type}<{ts_name}Response, {field_errors_tp}>> {{"
        );
    }

    // Explicit type parameters avoid phantom-type inference ambiguity: TypeScript cannot
    // infer Q/B/P/R/Fe from the spec value alone because EndpointSpec's type params are
    // phantom. Use `never` directly for absent roles so we avoid importing names just for
    // type params.
    let query_tp = if roles.has_query {
        format!("{ts_name}Query")
    } else {
        "never".to_owned()
    };
    let body_tp = if roles.has_body {
        format!("{ts_name}Body")
    } else {
        "never".to_owned()
    };
    let path_params_tp = if roles.has_path_params {
        format!("{ts_name}PathParams")
    } else {
        "never".to_owned()
    };
    let explicit_type_params =
        format!("{query_tp}, {body_tp}, {path_params_tp}, {ts_name}Response, {field_errors_tp}");

    let mut call_args: Vec<&str> = Vec::new();
    if roles.has_query {
        call_args.push("query");
    }
    if roles.has_body {
        call_args.push("body");
    }
    if roles.has_path_params {
        call_args.push("pathParams");
    }

    let call_endpoint_name = &config.call_endpoint_name;
    if call_args.is_empty() {
        let _ = writeln!(
            out,
            "    return {call_endpoint_name}<{explicit_type_params}>(spec, undefined, options);"
        );
    } else {
        let _ = writeln!(
            out,
            "    return {call_endpoint_name}<{explicit_type_params}>(spec, {{ {} }}, options);",
            call_args.join(", ")
        );
    }
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Rust type → TypeScript string conversion
// ---------------------------------------------------------------------------

/// Recursively convert a Rust `syn::Type` to a TypeScript type string.
/// Named types that are not primitives are added to `imports`.
///
/// Returns a [`syn::Error`] for any type that has no TypeScript equivalent
/// (e.g. slices, raw pointers, non-unit tuples, bare `Vec`/`Option` without
/// generic arguments).
pub(crate) fn rust_type_to_ts(ty: &Type, imports: &mut BTreeSet<String>) -> syn::Result<String> {
    match ty {
        // Unit tuple `()` → `null`
        Type::Tuple(TypeTuple { elems, .. }) if elems.is_empty() => Ok("null".to_owned()),

        // Non-unit tuple `(A, B, ...)` → `[A, B, ...]`
        Type::Tuple(TypeTuple { elems, .. }) => {
            let elem_ts = elems
                .iter()
                .map(|e| rust_type_to_ts(e, imports))
                .collect::<syn::Result<Vec<_>>>()?;
            Ok(format!("[{}]", elem_ts.join(", ")))
        }

        // Path types: primitives, Vec<T>, Option<T>, named types
        Type::Path(tp) => path_type_to_ts(ty, tp, imports),

        // Fixed-size array `[T; N]` → TypeScript tuple `[T, T, ..., T]` (N elements)
        Type::Array(arr) => {
            let elem_ts = rust_type_to_ts(&arr.elem, imports)?;
            let len = match &arr.len {
                syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Int(n),
                    ..
                }) => n.base10_parse::<usize>().map_err(|_| {
                    syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: array length is not a valid usize",
                    )
                })?,
                _ => {
                    return Err(syn::Error::new_spanned(
                        ty,
                        "#[api_endpoint]: only literal array lengths are supported \
                         in endpoint signatures",
                    ));
                }
            };
            let elems = std::iter::repeat_n(elem_ts.as_str(), len)
                .collect::<Vec<_>>()
                .join(", ");
            Ok(format!("[{elems}]"))
        }

        // Slice `[T]` → `Array<T>`
        Type::Slice(TypeSlice { elem, .. }) => {
            let inner_ts = rust_type_to_ts(elem, imports)?;
            Ok(format!("Array<{inner_ts}>"))
        }

        // Reference `&T` → treat as `T`
        Type::Reference(r) => rust_type_to_ts(&r.elem, imports),

        // Anything else (raw pointers, impl Trait, etc.) → error
        _ => Err(syn::Error::new_spanned(
            ty,
            "#[api_endpoint]: unsupported type in endpoint signature; only named types, \
             bool, numeric primitives, String/str/char, PathBuf/Path, Vec<T>, Option<T>, \
             Box<T>/Rc<T>/Arc<T>, Cow<T>, HashMap/BTreeMap/IndexMap<K,V>, \
             HashSet/BTreeSet/IndexSet<T>, [T; N], [T], (A, B, ...), () and &T are supported",
        )),
    }
}

fn path_type_to_ts(
    ty: &Type,
    tp: &TypePath,
    imports: &mut BTreeSet<String>,
) -> syn::Result<String> {
    let last = tp
        .path
        .segments
        .last()
        .expect("type path has at least one segment");
    let name = last.ident.to_string();

    match name.as_str() {
        "bool" => Ok("boolean".to_owned()),

        "f32" | "f64" | "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16" | "i32"
        | "i64" | "i128" | "isize" => Ok("number".to_owned()),

        // String types and char; also path types that serialize as strings
        "String" | "str" | "char" | "PathBuf" | "Path" => Ok("string".to_owned()),

        // Vec<T> → Array<T>
        "Vec" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments
                && let Some(GenericArgument::Type(inner)) = ab.args.first()
            {
                let inner_ts = rust_type_to_ts(inner, imports)?;
                return Ok(format!("Array<{inner_ts}>"));
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: `Vec` without a type argument is not supported \
                 in endpoint signatures",
            ))
        }

        // HashMap/BTreeMap/IndexMap<K, V> → Record<K, V>
        "HashMap" | "BTreeMap" | "IndexMap" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments {
                let mut type_args = ab.args.iter().filter_map(|a| {
                    if let GenericArgument::Type(t) = a {
                        Some(t)
                    } else {
                        None
                    }
                });
                if let (Some(k), Some(v)) = (type_args.next(), type_args.next()) {
                    let k_ts = rust_type_to_ts(k, imports)?;
                    let v_ts = rust_type_to_ts(v, imports)?;
                    return Ok(format!("Record<{k_ts}, {v_ts}>"));
                }
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: map type without two type arguments is not supported \
                 in endpoint signatures",
            ))
        }

        // HashSet<T> → Array<T>
        "HashSet" | "BTreeSet" | "IndexSet" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments
                && let Some(GenericArgument::Type(inner)) = ab.args.first()
            {
                let inner_ts = rust_type_to_ts(inner, imports)?;
                return Ok(format!("Array<{inner_ts}>"));
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: set type without a type argument is not supported \
                 in endpoint signatures",
            ))
        }

        // Box<T>/Rc<T>/Arc<T> → T (transparent wrappers)
        "Box" | "Rc" | "Arc" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments
                && let Some(GenericArgument::Type(inner)) = ab.args.first()
            {
                return rust_type_to_ts(inner, imports);
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: pointer type without a type argument is not supported \
                 in endpoint signatures",
            ))
        }

        // Cow<'a, T> → T (skip the lifetime, use the type argument)
        "Cow" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments
                && let Some(inner) = ab.args.iter().find_map(|a| {
                    if let GenericArgument::Type(t) = a {
                        Some(t)
                    } else {
                        None
                    }
                })
            {
                return rust_type_to_ts(inner, imports);
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: `Cow` without a type argument is not supported \
                 in endpoint signatures",
            ))
        }

        // Option<T> → T | null
        "Option" => {
            if let PathArguments::AngleBracketed(ab) = &last.arguments
                && let Some(GenericArgument::Type(inner)) = ab.args.first()
            {
                let inner_ts = rust_type_to_ts(inner, imports)?;
                return Ok(format!("{inner_ts} | null"));
            }
            Err(syn::Error::new_spanned(
                ty,
                "#[api_endpoint]: `Option` without a type argument is not supported \
                 in endpoint signatures",
            ))
        }

        // Everything else is treated as a named type from bindings/
        other => {
            imports.insert(other.to_owned());
            Ok(other.to_owned())
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use syn::Type;

    fn parse_type(s: &str) -> Type {
        syn::parse_str(s).expect("valid Rust type expression")
    }

    // ------------------------------------------------------------------
    // rust_type_to_ts: primitive conversions
    // ------------------------------------------------------------------

    #[test]
    fn ts_bool() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("bool"), &mut imp).unwrap(),
            "boolean"
        );
        assert!(imp.is_empty(), "no imports for primitives");
    }

    #[test]
    fn ts_numerics() {
        for ty in &[
            "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize",
            "f32", "f64",
        ] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "number",
                "numeric type {ty} should map to number"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_strings() {
        for ty in &["String", "str"] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "string",
                "string type {ty} should map to string"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_unit() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("()"), &mut imp).unwrap(),
            "null"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_vec() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Vec<u32>"), &mut imp).unwrap(),
            "Array<number>"
        );
        assert!(imp.is_empty(), "Vec<primitive> needs no imports");
    }

    #[test]
    fn ts_vec_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("Vec<CredentialInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "Array<CredentialInfo>");
        assert!(
            imp.contains("CredentialInfo"),
            "inner named type added to imports"
        );
    }

    #[test]
    fn ts_hashset() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("HashSet<u16>"), &mut imp).unwrap(),
            "Array<number>"
        );
        assert!(imp.is_empty(), "HashSet<primitive> needs no imports");
    }

    #[test]
    fn ts_hashset_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("HashSet<TagId>"), &mut imp).unwrap();
        assert_eq!(ts, "Array<TagId>");
        assert!(imp.contains("TagId"), "inner named type added to imports");
    }

    #[test]
    fn ts_option() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Option<String>"), &mut imp).unwrap(),
            "string | null"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_option_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("Option<UserInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "UserInfo | null");
        assert!(imp.contains("UserInfo"));
    }

    #[test]
    fn ts_named_type_adds_import() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("ProfileResponse"), &mut imp).unwrap();
        assert_eq!(ts, "ProfileResponse");
        assert!(imp.contains("ProfileResponse"));
    }

    // ------------------------------------------------------------------
    // rust_type_to_ts: unsupported types produce errors
    // ------------------------------------------------------------------

    #[test]
    fn ts_slice() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("[u8]"), &mut imp).unwrap(),
            "Array<number>"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_slice_ref() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("&[String]"), &mut imp).unwrap(),
            "Array<string>"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_non_unit_tuple() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("(u32, String)"), &mut imp).unwrap(),
            "[number, string]"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_tuple_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("(UserId, ProfileInfo)"), &mut imp).unwrap();
        assert_eq!(ts, "[UserId, ProfileInfo]");
        assert!(imp.contains("UserId"));
        assert!(imp.contains("ProfileInfo"));
    }

    #[test]
    fn ts_char() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("char"), &mut imp).unwrap(),
            "string"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_pathbuf() {
        for ty in &["PathBuf", "Path"] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "string",
                "{ty} should map to string"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_box() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Box<u32>"), &mut imp).unwrap(),
            "number"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_box_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("Box<UserInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "UserInfo");
        assert!(imp.contains("UserInfo"));
    }

    #[test]
    fn ts_rc_arc() {
        for ty in &["Rc<String>", "Arc<String>"] {
            let mut imp = BTreeSet::new();
            assert_eq!(
                rust_type_to_ts(&parse_type(ty), &mut imp).unwrap(),
                "string",
                "{ty} should be transparent"
            );
            assert!(imp.is_empty());
        }
    }

    #[test]
    fn ts_cow() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("Cow<'static, str>"), &mut imp).unwrap(),
            "string"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_hashmap() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("HashMap<String, u32>"), &mut imp).unwrap(),
            "Record<string, number>"
        );
        assert!(imp.is_empty());
    }

    #[test]
    fn ts_hashmap_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("HashMap<String, UserInfo>"), &mut imp).unwrap();
        assert_eq!(ts, "Record<string, UserInfo>");
        assert!(imp.contains("UserInfo"));
        assert!(
            !imp.contains("String"),
            "primitive key should not be imported"
        );
    }

    #[test]
    fn ts_btreemap() {
        let mut imp = BTreeSet::new();
        assert_eq!(
            rust_type_to_ts(&parse_type("BTreeMap<String, bool>"), &mut imp).unwrap(),
            "Record<string, boolean>"
        );
    }

    #[test]
    fn ts_vec_without_args_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("Vec"), &mut imp).is_err(),
            "bare Vec without type argument should not be silently accepted"
        );
    }

    #[test]
    fn ts_option_without_args_is_error() {
        let mut imp = BTreeSet::new();
        assert!(
            rust_type_to_ts(&parse_type("Option"), &mut imp).is_err(),
            "bare Option without type argument should not be silently accepted"
        );
    }

    #[test]
    fn ts_fixed_array_primitives() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[String; 10]"), &mut imp).unwrap();
        assert_eq!(
            ts,
            "[string, string, string, string, string, string, string, string, string, string]"
        );
        assert!(imp.is_empty(), "no imports for primitive element type");
    }

    #[test]
    fn ts_fixed_array_named() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[BackupCode; 3]"), &mut imp).unwrap();
        assert_eq!(ts, "[BackupCode, BackupCode, BackupCode]");
        assert!(
            imp.contains("BackupCode"),
            "inner named type added to imports"
        );
    }

    #[test]
    fn ts_fixed_array_size_zero() {
        let mut imp = BTreeSet::new();
        let ts = rust_type_to_ts(&parse_type("[u32; 0]"), &mut imp).unwrap();
        assert_eq!(ts, "[]");
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 1 — GET with query type
    // ------------------------------------------------------------------

    #[test]
    fn generate_get_with_query() {
        // FilterQuery and ProfileResponse have different names than the role aliases
        // (GetUsersProfileQuery, GetUsersProfileResponse), so they use the import + type alias path.
        let query = parse_type("FilterQuery");
        let response = ExtractedRole::Single(Box::new(parse_type("ProfileResponse")));
        let content = generate_ts_file(
            "GetUsersProfile",
            "GET",
            "users/profile",
            Some(&query),
            None,
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(
            content.contains("export const GetUsersProfileMethod = \"GET\" as const;"),
            "method const"
        );
        assert!(
            content.contains("export const GetUsersProfilePath   = \"users/profile\" as const;"),
            "path const"
        );
        assert!(
            content.contains("export type  GetUsersProfileQuery = FilterQuery;"),
            "query type alias"
        );
        assert!(
            content.contains("export type  GetUsersProfileBody = never;"),
            "body never alias"
        );
        assert!(
            content.contains("export type  GetUsersProfilePathParams = never;"),
            "path params never alias"
        );
        assert!(
            content.contains("export type  GetUsersProfileResponse = ProfileResponse;"),
            "response type alias"
        );
        assert!(
            content.contains("import type { FilterQuery } from \"../FilterQuery\";"),
            "query import"
        );
        assert!(
            content.contains("import type { ProfileResponse } from \"../ProfileResponse\";"),
            "response import"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: custom models_path prefix (APIM_MODELS_PATH)
    // ------------------------------------------------------------------

    #[test]
    fn generate_uses_custom_models_path() {
        let query = parse_type("FilterQuery");
        let response = ExtractedRole::Single(Box::new(parse_type("ProfileResponse")));
        let content = generate_ts_file(
            "GetUsersProfile",
            "GET",
            "users/profile",
            Some(&query),
            None,
            None,
            &response,
            None,
            "../models",
        )
        .unwrap();
        assert!(
            content.contains("import type { FilterQuery } from \"../models/FilterQuery\";"),
            "query import uses custom models_path"
        );
        assert!(
            content.contains("import type { ProfileResponse } from \"../models/ProfileResponse\";"),
            "response import uses custom models_path"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 2 — POST with body type (non-conflicting names)
    // ------------------------------------------------------------------

    #[test]
    fn generate_post_with_body() {
        // Use CredentialsBody as the body type: the role alias is LoginBody ≠ CredentialsBody,
        // so this exercises the import + type alias path (not the re-export path).
        let body = parse_type("CredentialsBody");
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let content = generate_ts_file(
            "Login",
            "POST",
            "auth/login",
            None,
            Some(&body),
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(content.contains("export const LoginMethod = \"POST\" as const;"));
        assert!(content.contains("export const LoginPath   = \"auth/login\" as const;"));
        assert!(content.contains("export type  LoginQuery = never;"));
        assert!(content.contains("export type  LoginBody = CredentialsBody;"));
        assert!(content.contains("export type  LoginPathParams = never;"));
        assert!(content.contains("export type  LoginResponse = ExpiresIn;"));
        assert!(content.contains("import type { CredentialsBody } from \"../CredentialsBody\";"));
        assert!(content.contains("import type { ExpiresIn } from \"../ExpiresIn\";"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: conflicting alias — uses re-export form
    // ------------------------------------------------------------------

    #[test]
    fn generate_conflicting_alias_uses_re_export() {
        // When the body type name equals the role alias name (e.g. endpoint "PatchInfo"
        // has body type PatchInfoBody → alias PatchInfoBody), TypeScript would error with
        // TS2440 if we emitted `export type PatchInfoBody = PatchInfoBody`. Instead we
        // keep the normal `import type { PatchInfoBody }` and emit `export type { PatchInfoBody }`
        // (bare re-export) so the local binding remains available to the `satisfies` block.
        let body = parse_type("PatchInfoBody");
        let response = ExtractedRole::Single(Box::new(parse_type("()")));
        let content = generate_ts_file(
            "PatchInfo",
            "PATCH",
            "user/info",
            None,
            Some(&body),
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        // The type is imported normally to create a local binding for the `satisfies` block.
        assert!(
            content.contains("import type { PatchInfoBody } from \"../PatchInfoBody\";"),
            "conflicting type must still appear as a regular import for local binding"
        );
        // Re-export form (no `from`): re-exports the local binding without triggering TS2440.
        assert!(
            content.contains("export type { PatchInfoBody };"),
            "conflicting body alias uses bare re-export form"
        );
        // The combined re-export-from form must NOT be used (it creates no local binding).
        assert!(
            !content.contains("export type { PatchInfoBody } from"),
            "combined re-export-from form must not be emitted"
        );
        // The standard type alias line must NOT be present
        assert!(
            !content.contains("export type  PatchInfoBody = PatchInfoBody;"),
            "conflicting alias form must not be emitted"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 3 — web::Path<String> → string (no import)
    // ------------------------------------------------------------------

    #[test]
    fn generate_with_string_path_params() {
        let path_params = parse_type("String");
        let response = ExtractedRole::Single(Box::new(parse_type("()")));
        let content = generate_ts_file(
            "DeleteCredential",
            "DELETE",
            "user/webauthn/credentials/{id}",
            None,
            None,
            Some(&path_params),
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(
            content.contains("export type  DeleteCredentialPathParams = string;"),
            "String path param → 'string' in TypeScript"
        );
        // `string` is a primitive — no import for it
        assert!(
            !content.contains("import type { string }"),
            "no spurious import for string primitive"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: case 4 — CustomizedJsonApiResult response
    // (at the ts_gen level this is just a named type in ExtractedRole::Single)
    // ------------------------------------------------------------------

    #[test]
    fn generate_customized_response() {
        // After the macro peels CustomizedJsonApiResult<T>, ts_gen only sees T.
        // So this verifies the Single(T) path with a non-conflicting name.
        let response = ExtractedRole::Single(Box::new(parse_type("UserEntry")));
        let content = generate_ts_file(
            "PatchUser",
            "PATCH",
            "users",
            None,
            None,
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(content.contains("export type  PatchUserResponse = UserEntry;"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: union response (Either<A, B>)
    // ------------------------------------------------------------------

    #[test]
    fn generate_union_response() {
        let response =
            ExtractedRole::Union(Box::new(parse_type("TypeA")), Box::new(parse_type("TypeB")));
        let content = generate_ts_file(
            "TestUnion",
            "GET",
            "test/union",
            None,
            None,
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(content.contains("export type  TestUnionResponse = TypeA | TypeB;"));
        assert!(content.contains("import type { TypeA } from \"../TypeA\";"));
        assert!(content.contains("import type { TypeB } from \"../TypeB\";"));
    }

    // ------------------------------------------------------------------
    // generate_ts_file: spec constant and EndpointSpec import
    // ------------------------------------------------------------------

    #[test]
    fn generate_ts_file_includes_endpoint_spec_import() {
        let response = ExtractedRole::Single(Box::new(parse_type("User")));
        let content = generate_ts_file(
            "GetUserInfo",
            "GET",
            "user/info",
            None,
            None,
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(
            content.contains("import type { EndpointSpec } from \"./EndpointSpec\";"),
            "EndpointSpec import should be present"
        );
        assert!(
            content.contains("satisfies EndpointSpec<"),
            "default export with satisfies clause should be present"
        );
        assert!(
            content.contains("GetUserInfoQuery,"),
            "spec type params should use role alias names"
        );
        assert!(
            content.contains("GetUserInfoResponse"),
            "spec type params should use role alias names"
        );
    }

    #[test]
    fn generate_ts_file_spec_default_export() {
        let body = parse_type("LoginBody");
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let content = generate_ts_file(
            "PostAuthLogin",
            "POST",
            "auth/login",
            None,
            Some(&body),
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(
            content.contains("export default {"),
            "spec should be a default export"
        );
        assert!(
            content.contains("method: PostAuthLoginMethod,"),
            "spec should reference method const"
        );
        assert!(
            content.contains("path: PostAuthLoginPath,"),
            "spec should reference path const"
        );
    }

    // ------------------------------------------------------------------
    // generate_ts_file: field_errors argument
    // ------------------------------------------------------------------

    #[test]
    fn generate_ts_file_with_field_errors_adds_role_and_spec_arg() {
        let body = parse_type("CredentialsBody");
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let field_errors = parse_type("CredentialsBodyFieldInvalidity");
        let content = generate_ts_file(
            "PostAuthLogin",
            "POST",
            "auth/login",
            None,
            Some(&body),
            None,
            &response,
            Some(&field_errors),
            "..",
        )
        .unwrap();
        assert!(
            content.contains(
                "export type  PostAuthLoginFieldErrors = CredentialsBodyFieldInvalidity;"
            ),
            "field-errors role alias"
        );
        assert!(
            content.contains(
                "import type { CredentialsBodyFieldInvalidity } from \"../CredentialsBodyFieldInvalidity\";"
            ),
            "field-errors type import"
        );
        assert!(
            content.contains(
                "satisfies EndpointSpec<\n    PostAuthLoginQuery,\n    PostAuthLoginBody,\n    PostAuthLoginPathParams,\n    PostAuthLoginResponse,\n    PostAuthLoginFieldErrors\n>;"
            ),
            "5-argument EndpointSpec instantiation when field_errors is set"
        );
    }

    #[test]
    fn generate_ts_file_without_field_errors_omits_role_and_spec_arg() {
        // Regression guard: omitting `field_errors` must keep emitting the original
        // 4-argument `EndpointSpec<...>` form (relying on `Fe`'s `never` default),
        // not `= never` of the role alias.
        let response = ExtractedRole::Single(Box::new(parse_type("ExpiresIn")));
        let content = generate_ts_file(
            "PostAuthLogout",
            "POST",
            "auth/logout",
            None,
            None,
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        assert!(!content.contains("FieldErrors"));
        assert!(
            content.contains(
                "satisfies EndpointSpec<\n    PostAuthLogoutQuery,\n    PostAuthLogoutBody,\n    PostAuthLogoutPathParams,\n    PostAuthLogoutResponse\n>;"
            ),
            "4-argument EndpointSpec instantiation when field_errors is absent"
        );
    }

    // ------------------------------------------------------------------
    // relative_module_dir
    // ------------------------------------------------------------------

    #[test]
    fn relative_module_dir_sibling_dirs() {
        assert_eq!(relative_module_dir("api", "endpoints"), "../endpoints");
    }

    #[test]
    fn relative_module_dir_deeper_nesting() {
        assert_eq!(
            relative_module_dir("api", "bindings/endpoints"),
            "../bindings/endpoints"
        );
    }

    #[test]
    fn relative_module_dir_shared_ancestor() {
        assert_eq!(
            relative_module_dir("v1/api", "v1/endpoints"),
            "../endpoints"
        );
    }

    #[test]
    fn relative_module_dir_same_directory() {
        assert_eq!(relative_module_dir("api", "api"), ".");
    }

    #[test]
    fn relative_module_dir_subdirectory() {
        assert_eq!(relative_module_dir("api", "api/endpoints"), "./endpoints");
    }

    // ------------------------------------------------------------------
    // generate_api_file
    // ------------------------------------------------------------------

    fn default_config() -> crate::config::MacroConfig {
        crate::config::MacroConfig::for_tests("client/services/http")
    }

    #[test]
    fn generate_api_import_is_relative_for_sibling_dirs() {
        // Regression test: APIM_EXPORT_DIR="bindings", APIM_ENDPOINTS_PATH="endpoints",
        // APIM_API_PATH="api" puts endpoints/ and api/ as sibling directories under bindings/.
        // The spec import must be filesystem-relative (`../endpoints/...`), not a bare
        // specifier (`endpoints/...`) that only resolves via a bundler baseUrl/alias.
        let mut config = default_config();
        config.export_dir = "bindings".to_owned();
        config.endpoints_path = "endpoints".to_owned();
        config.api_path = "api".to_owned();

        let content = generate_api_file(
            "GetLogComic",
            "getLogComic",
            ApiFileRoles {
                has_query: false,
                has_body: false,
                has_path_params: false,
                has_field_errors: false,
            },
            &config,
        );

        assert!(
            content.contains("import spec from \"../endpoints/GetLogComic\";"),
            "spec import is relative, not a bare specifier: {content}"
        );
        assert!(
            content
                .contains("import type { GetLogComicResponse } from \"../endpoints/GetLogComic\";"),
            "type import is relative, not a bare specifier: {content}"
        );
    }

    #[test]
    fn generate_api_get_with_query() {
        let content = generate_api_file(
            "GetUserInfo",
            "getUserInfo",
            ApiFileRoles {
                has_query: true,
                has_body: false,
                has_path_params: false,
                has_field_errors: false,
            },
            &default_config(),
        );
        assert!(
            content.contains("import spec from \"../bindings/endpoints/GetUserInfo\";"),
            "spec import is relative to the api file's own directory"
        );
        assert!(
            content.contains("import type { GetUserInfoQuery, GetUserInfoResponse }"),
            "type imports include only non-never role types"
        );
        // GetUserInfoBody and GetUserInfoPathParams are absent roles; `never` is emitted
        // directly in the callEndpoint<> type params so no import is needed.
        assert!(
            !content.contains("import type { GetUserInfoBody"),
            "body alias must not appear in the import type statement"
        );
        assert!(
            !content.contains("import type { GetUserInfoPathParams"),
            "pathParams alias must not appear in the import type statement"
        );
        assert!(
            content.contains("export async function getUserInfo("),
            "function exported with camelCase name"
        );
        assert!(
            content.contains("query?: GetUserInfoQuery,"),
            "optional query parameter"
        );
        assert!(
            content.contains("options?: Omit<RequestInit, \"method\">,"),
            "options parameter always present"
        );
        assert!(
            content.contains("): Promise<TypedApiResult<GetUserInfoResponse, never>> {"),
            "return type wraps Response in TypedApiResult"
        );
        assert!(
            content.contains("import type { TypedApiResult } from \"bindings/ApiResult\";"),
            "TypedApiResult imported from bindings"
        );
        // Absent roles use `never` directly in type params (not the alias name) so no extra import needed.
        assert!(
            content.contains(
                "callEndpoint<GetUserInfoQuery, never, never, GetUserInfoResponse, never>"
            ),
            "explicit type params: absent roles use never, not alias names"
        );
        assert!(
            content.contains("spec, { query }, options"),
            "query arg passed to callEndpoint with options"
        );
    }

    #[test]
    fn generate_api_post_with_body() {
        let content = generate_api_file(
            "PostAuthLogin",
            "postAuthLogin",
            ApiFileRoles {
                has_query: false,
                has_body: true,
                has_path_params: false,
                has_field_errors: false,
            },
            &default_config(),
        );
        assert!(
            content.contains("body: PostAuthLoginBody,"),
            "required body parameter"
        );
        assert!(
            !content.contains("query?:"),
            "no query parameter when has_query=false"
        );
        assert!(
            content.contains("spec, { body }, options"),
            "body arg passed to callEndpoint with options"
        );
    }

    #[test]
    fn generate_api_delete_with_path_params() {
        let content = generate_api_file(
            "DeleteUserWebauthnCredentialsId",
            "deleteUserWebauthnCredentialsId",
            ApiFileRoles {
                has_query: false,
                has_body: false,
                has_path_params: true,
                has_field_errors: false,
            },
            &default_config(),
        );
        assert!(
            content.contains("pathParams: DeleteUserWebauthnCredentialsIdPathParams,"),
            "required pathParams parameter"
        );
        assert!(
            content.contains("spec, { pathParams }, options"),
            "pathParams arg passed to callEndpoint with options"
        );
    }

    #[test]
    fn generate_api_no_params() {
        let content = generate_api_file(
            "PostAuthLogout",
            "postAuthLogout",
            ApiFileRoles {
                has_query: false,
                has_body: false,
                has_path_params: false,
                has_field_errors: false,
            },
            &default_config(),
        );
        assert!(!content.contains("query?:"), "no query parameter");
        assert!(!content.contains("body:"), "no body parameter");
        assert!(!content.contains("pathParams:"), "no pathParams parameter");
        // No args object — callEndpoint called with spec + undefined + options; all absent roles → never
        assert!(
            content.contains("callEndpoint<never, never, never, PostAuthLogoutResponse, never>(spec, undefined, options);"),
            "no args object when no params; all roles are never"
        );
    }

    #[test]
    fn generate_api_camel_case_name() {
        use heck::ToLowerCamelCase as _;
        assert_eq!("GetUserInfo".to_lower_camel_case(), "getUserInfo");
        assert_eq!(
            "PostAuthWebauthn2faComplete".to_lower_camel_case(),
            "postAuthWebauthn2faComplete"
        );
        assert_eq!(
            "DeleteUserWebauthnCredentialsId".to_lower_camel_case(),
            "deleteUserWebauthnCredentialsId"
        );
    }

    // ------------------------------------------------------------------
    // generate_api_file: unwrapped mode
    // ------------------------------------------------------------------

    fn unwrapped_config() -> crate::config::MacroConfig {
        let mut cfg = crate::config::MacroConfig::for_tests("client/services/http");
        cfg.unwrapped_response = true;
        cfg
    }

    #[test]
    fn generate_api_unwrapped_returns_raw_promise() {
        let content = generate_api_file(
            "GetUserInfo",
            "getUserInfo",
            ApiFileRoles {
                has_query: false,
                has_body: false,
                has_path_params: false,
                has_field_errors: false,
            },
            &unwrapped_config(),
        );
        assert!(
            content.contains("): Promise<GetUserInfoResponse> {"),
            "unwrapped mode uses bare Promise<R>, not Promise<ApiResult<R>>"
        );
        assert!(
            !content.contains("import type { ApiResult }"),
            "unwrapped mode must not import the result wrapper type"
        );
    }

    #[test]
    fn generate_api_wrapped_still_imports_result_type() {
        let content = generate_api_file(
            "GetUserInfo",
            "getUserInfo",
            ApiFileRoles {
                has_query: false,
                has_body: false,
                has_path_params: false,
                has_field_errors: false,
            },
            &default_config(),
        );
        assert!(
            content.contains("): Promise<TypedApiResult<GetUserInfoResponse, never>> {"),
            "wrapped mode keeps TypedApiResult in return type, with Fe defaulting to never"
        );
        assert!(
            content.contains("import type { TypedApiResult } from \"bindings/ApiResult\";"),
            "wrapped mode imports the result wrapper type"
        );
    }

    #[test]
    fn generate_api_with_field_errors_uses_typed_result() {
        let content = generate_api_file(
            "PostAuthLogin",
            "postAuthLogin",
            ApiFileRoles {
                has_query: false,
                has_body: true,
                has_path_params: false,
                has_field_errors: true,
            },
            &default_config(),
        );
        assert!(
            content.contains("import type { PostAuthLoginFieldErrors }")
                || content.contains(", PostAuthLoginFieldErrors }"),
            "field-errors type imported from the endpoint binding file"
        );
        assert!(
            content.contains("import type { TypedApiResult } from \"bindings/ApiResult\";"),
            "TypedApiResult imported instead of ApiResult when field_errors is set"
        );
        assert!(
            !content.contains("import type { ApiResult }"),
            "plain ApiResult must not be imported when field_errors is set"
        );
        assert!(
            content.contains(
                "): Promise<TypedApiResult<PostAuthLoginResponse, PostAuthLoginFieldErrors>> {"
            ),
            "return type uses TypedApiResult<R, Fe>"
        );
        assert!(
            content.contains(
                "callEndpoint<never, PostAuthLoginBody, never, PostAuthLoginResponse, PostAuthLoginFieldErrors>"
            ),
            "explicit type params include the 5th Fe argument"
        );
    }

    // ------------------------------------------------------------------
    // Imports are deduplicated and sorted alphabetically
    // ------------------------------------------------------------------

    #[test]
    fn imports_are_sorted_and_deduped() {
        // Use the same named type twice (in body and response) → one import
        let body = parse_type("SharedType");
        let response = ExtractedRole::Single(Box::new(parse_type("AnotherType")));
        let content = generate_ts_file(
            "TestDedup",
            "POST",
            "test/dedup",
            None,
            Some(&body),
            None,
            &response,
            None,
            "..",
        )
        .unwrap();
        let import_lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("import type"))
            .collect();
        // AnotherType and SharedType come from the BTreeSet (sorted); EndpointSpec is always last
        assert_eq!(import_lines.len(), 3);
        assert!(import_lines[0].contains("AnotherType"));
        assert!(import_lines[1].contains("SharedType"));
        assert!(import_lines[2].contains("EndpointSpec"));
    }
}
